### ISSUE TITLE
Conekta SDK on api 9

### ISSUE THREAD

**Issue by alfco333** [conekta/conekta-android#1]
Buenas tardes, tengo una pregunta, el SDK que ustedes proveen puede trabajar en API 9??

**Comment by MauricioMurga** [comment]
Hola @alfco333, no debería de haber ningún problema.

**Comment by nixho** [comment]
pregunta por que al momento de realizar el cargo no lo genera 
El recurso no ha sido encontrado.  -- 
 The object customer "cus_2oKctt2FXNkTww" could not be found
