### ISSUE TITLE
authentication_error

### ISSUE THREAD

**Issue by nericode** [conekta/conekta-android#17]
No puedo crear un token con la referencia de Android.

El error obtenido es el siguiente:

`{"object":"error","type":"authentication_error","message":"Unauthorized access, please check the permissions of your key for this call.","message_to_purchaser":"Acceso no autorizado.","param":null,"code":"authentication_error","validation_error":null}`

El token utilizado es: key_eYvWV7gSDkNYXsmr (El mismo de la documentación)

**Comment by joebottletech** [comment]
Hallo nericode Did you solve this issue ?
