### ISSUE TITLE
ClassNotFoundException: Didn't find class "org.apache.http.message.BasicNameValuePair"

### ISSUE THREAD

**Issue by JINC06** [conekta/conekta-android#22]
I had a problem using the conekta library on Android 9.

`java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/message/BasicNameValuePair;
        at io.conekta.conektasdk.Token.create(Token.java:41)
        at com.caffenio.app.fragments.payment.SummaryPaymentFragment.tokenizeCard(SummaryPaymentFragment.java:577)
        at com.caffenio.app.fragments.payment.SummaryPaymentFragment.lambda$onViewCreated$1(SummaryPaymentFragment.java:166)`

`Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.message.BasicNameValuePair" on path: DexPathList[[zip file "/data/app/`

I fix the problem adding the next lines on android manifest

android:usesCleartextTraffic="true"
on application

and inside
`<uses-library android:name="org.apache.http.legacy" android:required="false" />`

[https://imgur.com/hbtwrIA](url)

I hope someone who has the same problem could fix it

Best regards

**Comment by JINC06** [comment]
[](url)

**Comment by AdamPreneur** [comment]
Thanks @JINC06 You just saved my day.
