### ISSUE TITLE
Proguard y conekta-android

### ISSUE THREAD

**Issue by alfco333** [conekta/conekta-android#3]
Buenas tardes, hay alguna configuración especial de proguard que se tenga que agregar para poder utilizarlo con Conekta? ya que estoy estoy intentado generar el token pero me arroja un error que dice: "El recurso no ha sido encontrado".

**Comment by MauricioMurga** [comment]
Hola @alfco333, el error da a entender que se está intentando crear un cargo sin haber hecho la tokenización. En los logs de tu admin en Conekta debe de aparecer una llamada al endpoint de tokens seguido por el endpoint de charges. Para mayor soporte puedes escribirnos a soporte@conekta.io o llamar a nuestras oficinas: +52 (55) 4161-3535

**Comment by MauricioMurga** [comment]
Cerraré este issue por falta de actividad.

**Comment by paucuaram** [comment]
hi! a mi me pasa lo mismo en una aplicación asp .net mvc.

es por la misma razón?

**Comment by paucuaram** [comment]
@MauricioMurga a mi me pasa lo mismo en una app asp .net mvc. será por la misma razón del token??

**Comment by MauricioMurga** [comment]
Hola @paucuaram, el error indica que es esa la razón por la cual no puede generar el cargo. Si tienes algún id de log de Conekta podría revisarlo!

**Comment by paucuaram** [comment]
si, tengo.

**Comment by paucuaram** [comment]
@MauricioMurga te paso mi id de conecta?

**Comment by MauricioMurga** [comment]
Si gustas pasármelo a mi correo mauricio@conekta.io
