### ISSUE TITLE
Error en Conekta Android

### ISSUE THREAD

**Issue by faxterol** [conekta/conekta-android#4]
Hola buenas noches, tengo un problema con conekta que cuando quiero tokenizar una tarjeta me sale lo siguiente en el apartado de http logs

{
  "object": "error",
  "type": null,
  "message": "We can only process data from cards that have been properly tokenized or that come from a site that meets PCI compilance. If your site meets the standards , send a copy of your certificate and PCI contacto@conekta.io requests access.",
  "message_to_purchaser": "Solamente podemos procesar datos de tarjetas que han sido tokenizadas o que provengan de sitios seguros que cumplan los estándares de PCI.",
  "param": null,
  "code": "processing_error"
}

al principio si funcionaba pero despues me dio este problema... segun yo toma el certificado (que no deberia) de conekta java

agradezco la atención

**Comment by MauricioMurga** [comment]
Hola @Faxterol!, déjame revisar tu caso que no tiene mucho que ver con la librería. ¿Al hacer tus pruebas, estuviste cambiando de llaves del API?

Por favor, mándame un correo a mauricio@conekta.io con las llaves que estás utilizando y te doy una respuesta hoy.

Gracias!

**Comment by faxterol** [comment]
Hola Mauricio, lo resolvi hrs despues de hacer esta publicación

mi error: importaba el aar de tokenizer y el conekta java en mi app, lo cual era incorrecto esto ultimo, solo debía estar el aar del tokenizer, tengo más dudas con respecto al certificado, lo dejo en conekta-php

saludos

**Comment by MauricioMurga** [comment]
Hola @Faxterol. Efectivamente el aar contiente todo lo necesario para tokenizar.

No entiendo el comentario de conekta-php.

Quedo al pendiente si tienes más dudas!
